version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run cy:parallel
  post_build:
    commands:
      - aws s3 sync allure-report s3://reporte-de-pruebas-jose/
      - aws s3 cp --recursive --acl public-read s3://reporte-de-pruebas-jose/ s3://reporte-de-pruebas-jose/ --metadata-directive REPLACE
